### ISSUE TITLE
A few new STart Magainze coverdisks have been dumped

### ISSUE THREAD

**Issue by bbbradsmith** [ggnkua/Atari_ST_Sources#6]
Some issues of STart Magazine had interesting source code on their coverdisks. For a few months they used a weird format that was until now never dumped properly. The six affected issues are now available here:
https://archive.org/download/start_magazine_heidi_cover_disks/Disk%20Images/

Except for the last one (April 1990), they all seem to have source code that might be worth collecting. In particular the December 1989 issue includes the full source code for the RPG Avecta by Mark Swanson.

**Comment by ggnkua** [comment]
Hey, thanks for the heads up! A couple of months ago I went through all the STart cover disks I could find online and got a lot of source from those. Indeed I noticed that a few disks were not imaged properly (side 2 was missing). Cool that they've been imaged properly for preservation, and I was able to grab some sources from them!

On another note it's quite weird that their menu system warns about not being able to read from side B even though it seems fancy - you'd think that they could fix their disks instead of showing that messsage for months!

Anyway I'll commit all the STart sources soon and will close this ticket then.
